# numpy basic

In [2]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
one = np.array([1,2,90,4])

In [4]:
one.argmax()

np.int64(2)

In [5]:
one.argsort()               #index dega sorted order me

array([0, 1, 3, 2])

In [6]:
import numpy.char as char

In [7]:
x=[[1,2,3],[9,7,8],[6,5,4]]

In [8]:
ar = np.array(x)

In [9]:
ar

array([[1, 2, 3],
       [9, 7, 8],
       [6, 5, 4]])

In [10]:
ar.sum(axis=0)

array([16, 14, 15])

In [11]:
ar.sum(axis=1)

array([ 6, 24, 15])

In [35]:
ar.argmin()

np.int64(0)

In [36]:
ar.argmax()

np.int64(3)

In [37]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [1, 2, 0],
       [2, 1, 0]])

In [14]:
ar.sum()

np.int64(45)

In [15]:
ar

array([[1, 2, 3],
       [9, 7, 8],
       [6, 5, 4]])

In [16]:
import sys

In [20]:
py_ar=[0,4,55,2]

In [22]:
np_ar=np.array(py_ar)

In [23]:
np_ar.itemsize * np_ar.size

32

# NUMPY

In [33]:
array_size = int(input("Enter the size of the array: "))
array = [0] * array_size

for i in range(array_size):
    array[i] = int(input("Enter element {}: ".format(i+1)))

print("Array:", array)



Enter the size of the array:  5
Enter element 1:  3
Enter element 2:  4
Enter element 3:  6
Enter element 4:  8
Enter element 5:  9


Array: [3, 4, 6, 8, 9]


In [34]:
arr3= np.array([[[1,2,3],[5,6,7],[4,9,8]]])

In [35]:
arr3

array([[[1, 2, 3],
        [5, 6, 7],
        [4, 9, 8]]])

In [36]:
var = np.array(["A","B","C","D"])


In [37]:
var.dtype

dtype('<U1')

# linespace

In [6]:
# np.linspace(start_value,stop_value,num=50,endpoint=False,dtype=None)
A=np.linspace(2,20,10)
print(A)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
